language: php
notifications:
    email: false
php:
    - 5.6
    - 7.0
    - 7.1
script:
    - ./vendor/bin/phpcs --standard=PSR2 src
    - ./vendor/bin/phpunit
before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
